extern crate sdl2;
use self::sdl2::keyboard::Keycode;
use self::sdl2::keyboard::Keycode::*;
use std::mem;
// Taken from the SDL2 Rust binding keyboard mapping
#[derive(PartialEq, Clone, Debug)]
#[repr(u32)]
pub enum KeyboardKey {
    Backspace,
    Tab,
    Return,
    Escape,
    Space,
    Exclaim,
    Quotedbl,
    Hash,
    Dollar,
    Percent,
    Ampersand,
    Quote,
    LeftParen,
    RightParen,
    Asterisk,
    Plus,
    Comma,
    Minus,
    Period,
    Slash,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Colon,
    Semicolon,
    Less,
    Equals,
    Greater,
    Question,
    At,
    LeftBracket,
    Backslash,
    RightBracket,
    Caret,
    Underscore,
    Backquote,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Delete,
    CapsLock,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    PrintScreen,
    ScrollLock,
    Pause,
    Insert,
    Home,
    PageUp,
    End,
    PageDown,
    Right,
    Left,
    Down,
    Up,
    NumLockClear,
    KpDivide,
    KpMultiply,
    KpMinus,
    KpPlus,
    KpEnter,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    Kp0,
    KpPeriod,
    Application,
    Power,
    KpEquals,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Execute,
    Help,
    Menu,
    Select,
    Stop,
    Again,
    Undo,
    Cut,
    Copy,
    Paste,
    Find,
    Mute,
    VolumeUp,
    VolumeDown,
    KpComma,
    KpEqualsAS400,
    AltErase,
    Sysreq,
    Cancel,
    Clear,
    Prior,
    Return2,
    Separator,
    Out,
    Oper,
    ClearAgain,
    CrSel,
    ExSel,
    Kp00,
    Kp000,
    ThousandsSeparator,
    DecimalSeparator,
    CurrencyUnit,
    CurrencySubUnit,
    KpLeftParen,
    KpRightParen,
    KpLeftBrace,
    KpRightBrace,
    KpTab,
    KpBackspace,
    KpA,
    KpB,
    KpC,
    KpD,
    KpE,
    KpF,
    KpXor,
    KpPower,
    KpPercent,
    KpLess,
    KpGreater,
    KpAmpersand,
    KpDblAmpersand,
    KpVerticalBar,
    KpDblVerticalBar,
    KpColon,
    KpHash,
    KpSpace,
    KpAt,
    KpExclam,
    KpMemStore,
    KpMemRecall,
    KpMemClear,
    KpMemAdd,
    KpMemSubtract,
    KpMemMultiply,
    KpMemDivide,
    KpPlusMinus,
    KpClear,
    KpClearEntry,
    KpBinary,
    KpOctal,
    KpDecimal,
    KpHexadecimal,
    LCtrl,
    LShift,
    LAlt,
    LGui,
    RCtrl,
    RShift,
    RAlt,
    RGui,
    Mode,
    AudioNext,
    AudioPrev,
    AudioStop,
    AudioPlay,
    AudioMute,
    MediaSelect,
    Www,
    Mail,
    Calculator,
    Computer,
    AcSearch,
    AcHome,
    AcBack,
    AcForward,
    AcStop,
    AcRefresh,
    AcBookmarks,
    BrightnessDown,
    BrightnessUp,
    DisplaySwitch,
    KbdIllumToggle,
    KbdIllumDown,
    KbdIllumUp,
    Eject,
    Sleep,
}

impl KeyboardKey {
    pub fn from_keycode(e: Keycode) -> KeyboardKey {
        match e {
            Backspace => KeyboardKey:: Backspace,
            Tab => KeyboardKey:: Tab,
            Return => KeyboardKey::Return,
            Escape => KeyboardKey::Escape,
            Space => KeyboardKey::Space,
            Exclaim => KeyboardKey::Exclaim,
            Quotedbl => KeyboardKey::Quotedbl,
            Hash => KeyboardKey::Hash,
            Dollar => KeyboardKey::Dollar,
            Percent => KeyboardKey::Percent,
            Ampersand => KeyboardKey::Ampersand,
            Quote => KeyboardKey::Quote,
            LeftParen => KeyboardKey::LeftParen,
            RightParen => KeyboardKey::RightParen,
            Asterisk => KeyboardKey::Asterisk,
            Plus => KeyboardKey::Plus,
            Comma => KeyboardKey::Comma,
            Minus => KeyboardKey::Minus,
            Period => KeyboardKey::Period,
            Slash => KeyboardKey::Slash,
            Num0 => KeyboardKey::Num0,
            Num1 => KeyboardKey::Num1,
            Num2 => KeyboardKey::Num2,
            Num3 => KeyboardKey::Num3,
            Num4 => KeyboardKey::Num4,
            Num5 => KeyboardKey::Num5,
            Num6 => KeyboardKey::Num6,
            Num7 => KeyboardKey::Num7,
            Num8 => KeyboardKey::Num8,
            Num9 => KeyboardKey::Num9,
            Colon => KeyboardKey::Colon,
            Semicolon => KeyboardKey::Semicolon,
            Less => KeyboardKey::Less,
            Equals => KeyboardKey::Equals,
            Greater => KeyboardKey::Greater,
            Question => KeyboardKey::Question,
            At => KeyboardKey::At,
            LeftBracket => KeyboardKey::LeftBracket,
            Backslash => KeyboardKey::Backslash,
            RightBracket => KeyboardKey::RightBracket,
            Caret => KeyboardKey::Caret,
            Underscore => KeyboardKey::Underscore,
            Backquote => KeyboardKey::Backquote,
            A => KeyboardKey::A,
            B => KeyboardKey::B,
            C => KeyboardKey::C,
            D => KeyboardKey::D,
            E => KeyboardKey::E,
            F => KeyboardKey::F,
            G => KeyboardKey::G,
            H => KeyboardKey::H,
            I => KeyboardKey::I,
            J => KeyboardKey::J,
            K => KeyboardKey::K,
            L => KeyboardKey::L,
            M => KeyboardKey::M,
            N => KeyboardKey::N,
            O => KeyboardKey::O,
            P => KeyboardKey::P,
            Q => KeyboardKey::Q,
            R => KeyboardKey::R,
            S => KeyboardKey::S,
            T => KeyboardKey::T,
            U => KeyboardKey::U,
            V => KeyboardKey::V,
            W => KeyboardKey::W,
            X => KeyboardKey::X,
            Y => KeyboardKey::Y,
            Z => KeyboardKey::Z,
            Delete => KeyboardKey::Delete,
            CapsLock => KeyboardKey::CapsLock,
            F1 => KeyboardKey::F1,
            F2 => KeyboardKey::F2,
            F3 => KeyboardKey::F3,
            F4 => KeyboardKey::F4,
            F5 => KeyboardKey::F5,
            F6 => KeyboardKey::F6,
            F7 => KeyboardKey::F7,
            F8 => KeyboardKey::F8,
            F9 => KeyboardKey::F9,
            F10 => KeyboardKey::F10,
            F11 => KeyboardKey::F11,
            F12 => KeyboardKey::F12,
            PrintScreen => KeyboardKey::PrintScreen,
            ScrollLock => KeyboardKey::ScrollLock,
            Pause => KeyboardKey::Pause,
            Insert => KeyboardKey::Insert,
            Home => KeyboardKey::Home,
            PageUp => KeyboardKey::PageUp,
            End => KeyboardKey::End,
            PageDown => KeyboardKey::PageDown,
            Right => KeyboardKey::Right,
            Left => KeyboardKey::Left,
            Down => KeyboardKey::Down,
            Up => KeyboardKey::Up,
            NumLockClear => KeyboardKey::NumLockClear,
            KpDivide => KeyboardKey::KpDivide,
            KpMultiply => KeyboardKey::KpMultiply,
            KpMinus => KeyboardKey::KpMinus,
            KpPlus => KeyboardKey::KpPlus,
            KpEnter => KeyboardKey::KpEnter,
            Kp1 => KeyboardKey::Kp1,
            Kp2 => KeyboardKey::Kp2,
            Kp3 => KeyboardKey::Kp3,
            Kp4 => KeyboardKey::Kp4,
            Kp5 => KeyboardKey::Kp5,
            Kp6 => KeyboardKey::Kp6,
            Kp7 => KeyboardKey::Kp7,
            Kp8 => KeyboardKey::Kp8,
            Kp9 => KeyboardKey::Kp9,
            Kp0 => KeyboardKey::Kp0,
            KpPeriod => KeyboardKey::KpPeriod,
            Application => KeyboardKey::Application,
            Power => KeyboardKey::Power,
            KpEquals => KeyboardKey::KpEquals,
            F13 => KeyboardKey::F13,
            F14 => KeyboardKey::F14,
            F15 => KeyboardKey::F15,
            F16 => KeyboardKey::F16,
            F17 => KeyboardKey::F17,
            F18 => KeyboardKey::F18,
            F19 => KeyboardKey::F19,
            F20 => KeyboardKey::F20,
            F21 => KeyboardKey::F21,
            F22 => KeyboardKey::F22,
            F23 => KeyboardKey::F23,
            F24 => KeyboardKey::F24,
            Execute => KeyboardKey::
            Execute,
            Help => KeyboardKey::Help,
            Menu => KeyboardKey::Menu,
            Select => KeyboardKey::Select,
            Stop => KeyboardKey::Stop,
            Again => KeyboardKey::Again,
            Undo => KeyboardKey::Undo,
            Cut => KeyboardKey::Cut,
            Copy => KeyboardKey::Copy,
            Paste => KeyboardKey::Paste,
            Find => KeyboardKey::Find,
            Mute => KeyboardKey::Mute,
            VolumeUp => KeyboardKey::VolumeUp,
            VolumeDown => KeyboardKey::VolumeDown,
            KpComma => KeyboardKey::KpComma,
            KpEqualsAS400 => KeyboardKey::KpEqualsAS400,
            AltErase => KeyboardKey::AltErase,
            Sysreq => KeyboardKey::Sysreq,
            Cancel => KeyboardKey::Cancel,
            Clear => KeyboardKey::Clear,
            Prior => KeyboardKey::Prior,
            Return2 => KeyboardKey::Return2,
            Separator => KeyboardKey::Separator,
            Out => KeyboardKey::Out,
            Oper => KeyboardKey::Oper,
            ClearAgain => KeyboardKey::ClearAgain,
            CrSel => KeyboardKey::CrSel,
            ExSel => KeyboardKey::ExSel,
            Kp00 => KeyboardKey::Kp00,
            Kp000 => KeyboardKey::Kp000,
            ThousandsSeparator => KeyboardKey::ThousandsSeparator,
            DecimalSeparator => KeyboardKey::DecimalSeparator,
            CurrencyUnit => KeyboardKey::CurrencyUnit,
            CurrencySubUnit => KeyboardKey::CurrencySubUnit,
            KpLeftParen => KeyboardKey::KpLeftParen,
            KpRightParen => KeyboardKey::KpRightParen,
            KpLeftBrace => KeyboardKey::KpLeftBrace,
            KpRightBrace => KeyboardKey::KpRightBrace,
            KpTab => KeyboardKey::KpTab,
            KpBackspace => KeyboardKey::KpBackspace,
            KpA => KeyboardKey::KpA,
            KpB => KeyboardKey::KpB,
            KpC => KeyboardKey::KpC,
            KpD => KeyboardKey::KpD,
            KpE => KeyboardKey::KpE,
            KpF => KeyboardKey::KpF,
            KpXor => KeyboardKey::KpXor,
            KpPower => KeyboardKey::KpPower,
            KpPercent => KeyboardKey::KpPercent,
            KpLess => KeyboardKey::KpLess,
            KpGreater => KeyboardKey::KpGreater,
            KpAmpersand => KeyboardKey::KpAmpersand,
            KpDblAmpersand => KeyboardKey::KpDblAmpersand,
            KpVerticalBar => KeyboardKey::KpVerticalBar,
            KpDblVerticalBar => KeyboardKey::KpDblVerticalBar,
            KpColon => KeyboardKey::KpColon,
            KpHash => KeyboardKey::KpHash,
            KpSpace => KeyboardKey::KpSpace,
            KpAt => KeyboardKey::KpAt,
            KpExclam => KeyboardKey::KpExclam,
            KpMemStore => KeyboardKey::KpMemStore,
            KpMemRecall => KeyboardKey::KpMemRecall,
            KpMemClear => KeyboardKey::KpMemClear,
            KpMemAdd => KeyboardKey::KpMemAdd,
            KpMemSubtract => KeyboardKey::KpMemSubtract,
            KpMemMultiply => KeyboardKey::KpMemMultiply,
            KpMemDivide => KeyboardKey::KpMemDivide,
            KpPlusMinus => KeyboardKey::KpPlusMinus,
            KpClear => KeyboardKey::KpClear,
            KpClearEntry => KeyboardKey::KpClearEntry,
            KpBinary => KeyboardKey::KpBinary,
            KpOctal => KeyboardKey::KpOctal,
            KpDecimal => KeyboardKey::KpDecimal,
            KpHexadecimal => KeyboardKey::KpHexadecimal,
            LCtrl => KeyboardKey::LCtrl,
            LShift => KeyboardKey::LShift,
            LAlt => KeyboardKey::LAlt,
            LGui => KeyboardKey::LGui,
            RCtrl => KeyboardKey::RCtrl,
            RShift => KeyboardKey::RShift,
            RAlt => KeyboardKey::RAlt,
            RGui => KeyboardKey::RGui,
            Mode => KeyboardKey::Mode,
            AudioNext => KeyboardKey::AudioNext,
            AudioPrev => KeyboardKey::AudioPrev,
            AudioStop => KeyboardKey::AudioStop,
            AudioPlay => KeyboardKey::AudioPlay,
            AudioMute => KeyboardKey::AudioMute,
            MediaSelect => KeyboardKey::MediaSelect,
            Www => KeyboardKey::Www,
            Mail => KeyboardKey::Mail,
            Calculator => KeyboardKey::Calculator,
            Computer => KeyboardKey::Computer,
            AcSearch => KeyboardKey::AcSearch,
            AcHome => KeyboardKey::AcHome,
            AcBack => KeyboardKey::AcBack,
            AcForward => KeyboardKey::AcForward,
            AcStop => KeyboardKey::AcStop,
            AcRefresh => KeyboardKey::
            AcRefresh,
            AcBookmarks => KeyboardKey::AcBookmarks,
            BrightnessDown => KeyboardKey::BrightnessDown,
            BrightnessUp => KeyboardKey::BrightnessUp,
            DisplaySwitch => KeyboardKey::DisplaySwitch,
            KbdIllumToggle => KeyboardKey::KbdIllumToggle,
            KbdIllumDown => KeyboardKey::KbdIllumDown,
            KbdIllumUp => KeyboardKey::KbdIllumUp,
            Eject => KeyboardKey::Eject,
            Sleep => KeyboardKey::Sleep,
        }
    }
}